"""Metodos CRUD

Revision ID: 20f7dc35d7bb
Revises: 4df4a28f13b7
Create Date: 2026-06-18 16:53:08.787891

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '20f7dc35d7bb'
down_revision: Union[str, None] = '4df4a28f13b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###